name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests on JDK ${{matrix.java-version}} (${{matrix.os}})
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11, 17 ]
        os: [ 'ubuntu-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        name: Setup java
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'
      - name: Build core with Maven
        working-directory: ./stryker4jvm-core
        run: mvn clean install
      - name: Setup Gradle and build Kotlin Mutator
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9.1
          build-root-directory: ./stryker4jvm-mutator-kotlin
          arguments: |
            clean build
            publishToMavenLocal
      - name: Run tests
        run: sbt test

  sbt-scripted:
    name: sbt plugin scripted tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'sbt'
      - name: Build core with Maven
        working-directory: ./stryker4jvm-core
        run: mvn clean install
      - name: Setup Gradle and build Kotlin Mutator
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9.1
          build-root-directory: ./stryker4jvm-mutator-kotlin
          arguments: |
            clean build
            publishToMavenLocal
      - name: Run scripted test
        run: sbt 'stryker4jvm2_12/publishLocal; stryker4jvm-mutator-scala2_12/publishLocal; stryker4jvm-api2_12/publishLocal; stryker4jvm-plugin-sbt-testrunner2_12/publishLocal; scripted sbt-stryker4jvm/test-1'

  maven-plugin:
    name: Test Maven plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cleanup M2
        run: rm -rf ~/.m2/repository/io/stryker-mutator/*/SET-BY-SBT-SNAPSHOT/
      - name: Build core with Maven
        working-directory: ./stryker4jvm-core
        run: mvn clean install
      - name: Setup Gradle and build Kotlin Mutator
        uses: gradle/gradle-build-action@v2
        with:
         gradle-version: 6.9.1
         build-root-directory: ./stryker4jvm-mutator-kotlin
         arguments: |
           clean build
           publishToMavenLocal
      - name: Publish stryker4jvm
        run: sbt 'publishM2Local'
      - name: Run Maven tests
        working-directory: ./stryker4jvm-plugin-maven
        run: mvn verify -B --no-transfer-progress

  formatting:
    name: Test formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
        with:
          extraFiles: 'bin/scalafmt,.scalafmt.conf'
          extraKey: 'scalafmt'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Test formatting
        run: ./bin/scalafmt --test

  release:
    needs: [test, sbt-scripted, maven-plugin, formatting]
    if: "github.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      # Fetch all tags
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v3
        name: Setup java
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'sbt'
      - name: Build core with Maven
        working-directory: ./stryker4jvm-core
        run: mvn clean install
      - name: Setup Gradle and build Kotlin Mutator
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9.1
          build-root-directory: ./stryker4jvm-mutator-kotlin
          arguments: |
            clean build
            publishToMavenLocal
      - name: Publish
        run: sbt ci-release
        env:
          CI_RELEASE: stryker4jvmPublishSigned
          CI_SONATYPE_RELEASE: stryker4jvmReleaseAll
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
