name: mutation testing

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - test/**

jobs:
  stryker4jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 15
          cache: 'sbt'
      - name: Build core with Maven
        working-directory: ./stryker4jvm-core
        run: mvn clean install
      - name: Setup Gradle and build Kotlin Mutator
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9.1
          build-root-directory: ./stryker4jvm-mutator-kotlin
          arguments: |
            clean build
            publishToMavenLocal
      - name: Create Stryker4s config
        run: echo 'stryker4s{reporters=["console","dashboard"],base-dir="core",dashboard.module="core"}' > stryker4s.conf
      - name: Run stryker on Stryker4jvm
        run: sbt 'project stryker4jvm; stryker'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  mutator-scala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 15
          cache: 'sbt'
      - name: Build core with Maven
        working-directory: ./stryker4jvm-core
        run: mvn clean install
      - name: Setup Gradle and build Kotlin Mutator
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9.1
          build-root-directory: ./stryker4jvm-mutator-kotlin
          arguments: |
            clean build
            publishToMavenLocal
      - name: Create Stryker4s config
        run: echo 'stryker4s{reporters=["console","dashboard"],base-dir="stryker4jvm-mutator-scala",dashboard.module="stryker4jvm-mutator-scala"}' > stryker4s.conf
      - name: Run stryker on Stryker4jvm
        run: sbt 'project stryker4jvm-mutator-scala; stryker'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  command-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 15
          cache: 'sbt'
      - name: Build core with Maven
        working-directory: ./stryker4jvm-core
        run: mvn clean install
      - name: Setup Gradle and build Kotlin Mutator
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9.1
          build-root-directory: ./stryker4jvm-mutator-kotlin
          arguments: |
            clean build
            publishToMavenLocal
      - name: Create Stryker4s config
        run: echo 'stryker4s{reporters=["console","dashboard"],base-dir="command-runner",dashboard.module="command-runner"}' > stryker4s.conf
      - name: Run stryker on the command runner
        run: sbt 'project stryker4jvm-command-runner; stryker'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  maven-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 15
          cache: 'maven'
      - name: Build core with Maven
        working-directory: ./stryker4jvm-core
        run: mvn clean install
      - name: Setup Gradle and build Kotlin Mutator
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9.1
          build-root-directory: ./stryker4jvm-mutator-kotlin
          arguments: |
            clean build
            publishToMavenLocal
      - name: Publish Stryker4jvm maven deps locally
        run: sbt publishM2Local
      - name: Create Stryker4s config
        run: echo 'stryker4s{reporters=["console","dashboard"],base-dir="stryker4jvm-plugin-maven",dashboard.module="stryker4jvm-plugin-maven"}' > stryker4s.conf
      - name: Run Stryker4s maven plugin on Stryker4jvm-plugin-maven
        working-directory: ./stryker4jvm-plugin-maven
        run: mvn -B --no-transfer-progress stryker4s:run
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
